/**
 * Environment variables that control inference routing: which provider to use,
 * which endpoint to hit, and which model IDs to send.
 *
 * When OPEN_CODE_CLI_PROVIDER_MANAGED_BY_HOST is truthy in the spawn env, these
 * are stripped from settings-sourced env so the host's routing config isn't
 * overridden by a user's ~/.open-code-cli/settings.json.
 *
 * @[MODEL LAUNCH]: New models usually don't need changes here —
 * New providers or new routing config vars (endpoint, project, auth) do.
 */
const PROVIDER_MANAGED_ENV_VARS = new Set([
  // The flag itself — settings can't unset it once the host set it
  'OPEN_CODE_CLI_PROVIDER_MANAGED_BY_HOST',
  // Provider selection
  // Endpoint config (base URLs, project/resource identifiers)
  'OPEN_CODE_CLI_PROVIDER_BASE_URL',
  'OPEN_CODE_CLI_BASE_URL',
  'OPEN_CODE_CLI_REMOTE_BASE_URL',
  'OPEN_CODE_CLI_PROVIDER_RESOURCE',
  'OPEN_CODE_CLI_PROVIDER_PROJECT_ID',
  // Auth
  'OPEN_CODE_CLI_API_KEY',
  'OPEN_CODE_CLI_AUTH_TOKEN',
  // Model defaults — often set to provider-specific ID formats
  'OPEN_CODE_CLI_MODEL',
  'OPEN_CODE_CLI_DEFAULT_SMALL_FAST_MODEL',
  'OPEN_CODE_CLI_DEFAULT_SMALL_FAST_MODEL_DESCRIPTION',
  'OPEN_CODE_CLI_DEFAULT_SMALL_FAST_MODEL_NAME',
  'OPEN_CODE_CLI_DEFAULT_SMALL_FAST_MODEL_SUPPORTED_CAPABILITIES',
  'OPEN_CODE_CLI_DEFAULT_BEST_MODEL',
  'OPEN_CODE_CLI_DEFAULT_BEST_MODEL_DESCRIPTION',
  'OPEN_CODE_CLI_DEFAULT_BEST_MODEL_NAME',
  'OPEN_CODE_CLI_DEFAULT_BEST_MODEL_SUPPORTED_CAPABILITIES',
  'OPEN_CODE_CLI_DEFAULT_MODEL',
  'OPEN_CODE_CLI_DEFAULT_MODEL_DESCRIPTION',
  'OPEN_CODE_CLI_DEFAULT_MODEL_NAME',
  'OPEN_CODE_CLI_DEFAULT_MODEL_SUPPORTED_CAPABILITIES',
  'OPEN_CODE_CLI_SMALL_FAST_MODEL',
  'OPEN_CODE_CLI_SMALL_FAST_MODEL_AWS_REGION',
  'OPEN_CODE_CLI_SUBAGENT_MODEL',
])

const PROVIDER_MANAGED_ENV_PREFIXES: string[] = []

export function isProviderManagedEnvVar(key: string): boolean {
  const upper = key.toUpperCase()
  return (
    PROVIDER_MANAGED_ENV_VARS.has(upper) ||
    PROVIDER_MANAGED_ENV_PREFIXES.some(p => upper.startsWith(p))
  )
}

/**
 * Dangerous shell settings that can execute arbitrary shell code
 */
export const DANGEROUS_SHELL_SETTINGS = [
  'apiKeyHelper',
  'awsAuthRefresh',
  'awsCredentialExport',
  'gcpAuthRefresh',
  'otelHeadersHelper',
  'statusLine',
] as const

/**
 * Safe environment variables that can be applied before trust dialog.
 * These are Open Code CLI specific settings that don't pose security risks.
 *
 * IMPORTANT: This is the source of truth for which env vars are safe.
 * Any env var NOT in this list is considered dangerous and will trigger
 * a security dialog when set via remote managed settings.
 *
 * Dangerous env vars (NOT in this list):
 *
 * === REDIRECT TO ATTACKER-CONTROLLED SERVER ===
 * - OPEN_CODE_CLI_PROVIDER_BASE_URL, OPEN_CODE_CLI_BASE_URL, OPEN_CODE_CLI_REMOTE_BASE_URL
 * - HTTP_PROXY, HTTPS_PROXY, NO_PROXY, http_proxy, https_proxy, no_proxy
 * - OTEL_EXPORTER_OTLP_ENDPOINT, OTEL_EXPORTER_OTLP_LOGS_ENDPOINT, OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
 *
 * === TRUST ATTACKER-CONTROLLED SERVER ===
 * - NODE_TLS_REJECT_UNAUTHORIZED
 * - NODE_EXTRA_CA_CERTS
 *
 * === SWITCH TO ATTACKER-CONTROLLED PROJECT ===
 * - OPEN_CODE_CLI_PROVIDER_RESOURCE
 * - OPEN_CODE_CLI_API_KEY, OPEN_CODE_CLI_AUTH_TOKEN
 */
export const SAFE_ENV_VARS = new Set([
  'OPEN_CODE_CLI_CUSTOM_HEADERS',
  'OPEN_CODE_CLI_CUSTOM_MODEL_OPTION',
  'OPEN_CODE_CLI_CUSTOM_MODEL_OPTION_DESCRIPTION',
  'OPEN_CODE_CLI_CUSTOM_MODEL_OPTION_NAME',
  'OPEN_CODE_CLI_DEFAULT_SMALL_FAST_MODEL',
  'OPEN_CODE_CLI_DEFAULT_SMALL_FAST_MODEL_DESCRIPTION',
  'OPEN_CODE_CLI_DEFAULT_SMALL_FAST_MODEL_NAME',
  'OPEN_CODE_CLI_DEFAULT_SMALL_FAST_MODEL_SUPPORTED_CAPABILITIES',
  'OPEN_CODE_CLI_DEFAULT_BEST_MODEL',
  'OPEN_CODE_CLI_DEFAULT_BEST_MODEL_DESCRIPTION',
  'OPEN_CODE_CLI_DEFAULT_BEST_MODEL_NAME',
  'OPEN_CODE_CLI_DEFAULT_BEST_MODEL_SUPPORTED_CAPABILITIES',
  'OPEN_CODE_CLI_DEFAULT_MODEL',
  'OPEN_CODE_CLI_DEFAULT_MODEL_DESCRIPTION',
  'OPEN_CODE_CLI_DEFAULT_MODEL_NAME',
  'OPEN_CODE_CLI_DEFAULT_MODEL_SUPPORTED_CAPABILITIES',
  'OPEN_CODE_CLI_API_KEY',
  'OPEN_CODE_CLI_MODEL',
  'OPEN_CODE_CLI_SMALL_FAST_MODEL',
  'BASH_DEFAULT_TIMEOUT_MS',
  'BASH_MAX_OUTPUT_LENGTH',
  'BASH_MAX_TIMEOUT_MS',
  'OPEN_CODE_BASH_MAINTAIN_PROJECT_WORKING_DIR',
  'OPEN_CODE_CLI_API_KEY_HELPER_TTL_MS',
  'OPEN_CODE_CLI_DISABLE_EXPERIMENTAL_BETAS',
  'OPEN_CODE_CLI_DISABLE_NONESSENTIAL_TRAFFIC',
  'OPEN_CODE_CLI_DISABLE_TERMINAL_TITLE',
  'OPEN_CODE_CLI_ENABLE_TELEMETRY',
  'OPEN_CODE_CLI_EXPERIMENTAL_AGENT_TEAMS',
  'OPEN_CODE_CLI_IDE_SKIP_AUTO_INSTALL',
  'OPEN_CODE_CLI_MAX_OUTPUT_TOKENS',
  'OPEN_CODE_CLI_SUBAGENT_MODEL',
  'DISABLE_AUTOUPDATER',
  'DISABLE_BUG_COMMAND',
  'DISABLE_COST_WARNINGS',
  'DISABLE_ERROR_REPORTING',
  'DISABLE_FEEDBACK_COMMAND',
  'DISABLE_TELEMETRY',
  'ENABLE_TOOL_SEARCH',
  'MAX_MCP_OUTPUT_TOKENS',
  'MAX_THINKING_TOKENS',
  'MCP_TIMEOUT',
  'MCP_TOOL_TIMEOUT',
  'OTEL_EXPORTER_OTLP_HEADERS',
  'OTEL_EXPORTER_OTLP_LOGS_HEADERS',
  'OTEL_EXPORTER_OTLP_LOGS_PROTOCOL',
  'OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE',
  'OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY',
  'OTEL_EXPORTER_OTLP_METRICS_HEADERS',
  'OTEL_EXPORTER_OTLP_METRICS_PROTOCOL',
  'OTEL_EXPORTER_OTLP_PROTOCOL',
  'OTEL_EXPORTER_OTLP_TRACES_HEADERS',
  'OTEL_LOG_TOOL_DETAILS',
  'OTEL_LOG_USER_PROMPTS',
  'OTEL_LOGS_EXPORT_INTERVAL',
  'OTEL_LOGS_EXPORTER',
  'OTEL_METRIC_EXPORT_INTERVAL',
  'OTEL_METRICS_EXPORTER',
  'OTEL_METRICS_INCLUDE_ACCOUNT_UUID',
  'OTEL_METRICS_INCLUDE_SESSION_ID',
  'OTEL_METRICS_INCLUDE_VERSION',
  'OTEL_RESOURCE_ATTRIBUTES',
  'USE_BUILTIN_RIPGREP',
])
